// Dữ liệu Đề 3 - Nhập môn mật mã học
// Nguồn: Đề NMMMH(xin được)/Đề 3 (16 ảnh, 30 câu)
// Đáp án được ghi khi ảnh nguồn có đánh dấu rõ ràng.

var NMMMH_DE3_DATA = {
  subjectId: 'nmmmh',
  subjectName: 'Nhập môn mật mã học',
  subjectIcon: '🔐',
  subjectColor: '#0ea5e9',
  batchKey: 'nmmmh_seed_v3',
  sourceSet: 'Đề 3',
  questions: [
    { "id":"nmmmh_d3_1","type":"choice","num":"D3_1","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Lựa chọn đáp án SAI","options":[{"id":"a","text":"Tấn công vét cạn đối với hệ mật Vigenere, kẻ tấn công tới đa phải thử 26^m khóa"},{"id":"b","text":"Hệ mật Affine có khóa là các cặp (a,b) thuộc Z26"},{"id":"c","text":"Hệ mật Ceasar có số lượng khóa là 26"},{"id":"d","text":"Hệ mật khóa chạy dựa trên hệ mật Vigenere nhưng khóa không có tính chu kì"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224644.png","needs_check":true},
    { "id":"nmmmh_d3_2","type":"choice","num":"D3_2","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Phát biểu nào về hệ mã OTP sau đây là SAI?","options":[{"id":"a","text":"Là hệ mật có độ mật hoàn thiện"},{"id":"b","text":"Phép mã và giải mã là đồng nhất."},{"id":"c","text":"Là hệ mật khóa đối xứng"},{"id":"d","text":"|K| < |P|"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224644.png","needs_check":true},
    { "id":"nmmmh_d3_3","type":"choice","num":"D3_3","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Giả sử 2 bên sử dụng mã dịch vòng và bản mã truyền đi là \"CFMVCPURP\" thu. Hãy chọn khóa K đúng","options":[{"id":"a","text":"3"},{"id":"b","text":"21"},{"id":"c","text":"9"},{"id":"d","text":"17"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224707.png","needs_check":true},
    { "id":"nmmmh_d3_4","type":"choice","num":"D3_4","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Lựa chọn khẳng định ĐÚNG","options":[{"id":"a","text":"Hệ mật khóa chạy có khóa được nối tiếp bằng một phần của bản rõ để đạt độ dài bằng bản rõ"},{"id":"b","text":"Lực lượng khóa của hệ mã dịch vòng là 26!"},{"id":"c","text":"Hệ mật thay thế đơn biểu là hệ mật đơn giản, được thực hiện bằng cách thay thế 1 kí tự bằng 2 kí tự khác nhau"},{"id":"d","text":"Lực lượng khóa của hệ mã Vigenere 26^3"}],"answer":"d","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224811.png","needs_check":false},
    { "id":"nmmmh_d3_5","type":"choice","num":"D3_5","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"A và B lựa chọn hệ mật hoán vị với quy tắc: viết bản rõ theo từng hàng thành ma trận mat(1,2,3,4,5,6;7,8,9,10,11,12;13,14,15,16,17,18;19,20,21,22,23,24). Sau đó tạo ra bản mã bằng cách lấy các cột của ma trận này. B nhận được bản mã \"HKNAAHGNTOKTAAHONCAAGOIN\". Hãy giúp B lựa chọn đáp án đúng cho các vị trí (8;16;19;23) trong bản rõ.","options":[{"id":"a","text":"HHOO"},{"id":"b","text":"HHKK"},{"id":"c","text":"HHAA"},{"id":"d","text":"HHNN"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224831.png","needs_check":true},
    { "id":"nmmmh_d3_6","type":"choice","num":"D3_6","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Hệ mật đa biểu Vigenere dựa vào hệ mật nào sau đây?","options":[{"id":"a","text":"DES"},{"id":"b","text":"Affine"},{"id":"c","text":"Dịch vòng"},{"id":"d","text":"Hill"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224912.png","needs_check":true},
    { "id":"nmmmh_d3_7","type":"choice","num":"D3_7","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"A và B sử dụng hệ mật Affine để trao đổi thông tin, B nhận được bản mã \"HERQPCERHXEFDHFQPXEDT\". Biết \"H\" là mã hóa của \"C\", \"E\" là mã hóa của \"H\". Hãy giúp B tìm các kí tự của bản rõ ở các vị trí a, b, c, d trong sơ đồ.","image":"images/nmmmh/source_crops/de3/d3_7_positions.png","options":[{"id":"a","text":"NVHG"},{"id":"b","text":"NVHH"},{"id":"c","text":"NNHG"},{"id":"d","text":"NUHG"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224912.png","needs_check":true},
    { "id":"nmmmh_d3_8","type":"choice","num":"D3_8","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Giả sử ta có bản rõ 'week' được mã hóa bằng hệ mã Hill với m = 2, bản mã nhận được là MWWU. Hãy chọn khóa mã hóa đúng","options":[{"id":"a","text":"Bred"},{"id":"b","text":"Frid"},{"id":"c","text":"Brid"},{"id":"d","text":"Fred"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224955.png","needs_check":true},
    { "id":"nmmmh_d3_9","type":"choice","num":"D3_9","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Đâu là bản rõ của bản mã \"QCTO\" thu được khi dùng hệ mã Hill với ma trận khóa k⁻¹ = mat(23,18;22,19)?","options":[{"id":"a","text":"WHEN"},{"id":"b","text":"WORK"},{"id":"c","text":"WEEK"},{"id":"d","text":"WHAT"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 224955.png","needs_check":true},
    { "id":"nmmmh_d3_10","type":"choice","num":"D3_10","chapter":1,"chapter_name":"Mật mã cổ điển","prompt":"Đâu là bản mã của bản rõ \"PHUONGPHAPKISO\" được mã bởi hệ mã Vigenere với khóa k = \"KHONG\"?","options":[{"id":"a","text":"ZOIBRQWVNTUPGB"},{"id":"b","text":"ZOIBRTWVNTUPGB"},{"id":"c","text":"ZOIBRQWVNTUPGE"},{"id":"d","text":"ZOIBTQWVNVUPGB"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 225040.png","needs_check":true},
    { "id":"nmmmh_d3_11","type":"choice","num":"D3_11","chapter":2,"chapter_name":"DES","prompt":"Số vòng, độ dài khóa, độ lớn khối dữ liệu đầu vào trong thuật toán DES lần lượt là:","options":[{"id":"a","text":"12; 64; 64"},{"id":"b","text":"16; 64;128"},{"id":"c","text":"16; 56; 64"},{"id":"d","text":"10; 56; 64"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 225944.png","needs_check":true},
    { "id":"nmmmh_d3_12","type":"choice","num":"D3_12","chapter":2,"chapter_name":"DES","prompt":"Nguyên lí thiết kế mã khối của Shannon bao gồm:","options":[{"id":"a","text":"Xáo trộn và thay thế"},{"id":"b","text":"Khuếch tán, hoán vị và thay thế"},{"id":"c","text":"Xáo trộn và khuếch tán."},{"id":"d","text":"Xáo trộn và hoán vị"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 225944.png","needs_check":true},
    { "id":"nmmmh_d3_13","type":"choice","num":"D3_13","chapter":2,"chapter_name":"DES","prompt":"Hệ mã nào sau đây là hệ mã khối?","options":[{"id":"a","text":"AES, Affine, RC4"},{"id":"b","text":"DES, AES"},{"id":"c","text":"DES, AES, Ceasar."},{"id":"d","text":"DES, AES, Affine,"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 225944.png","needs_check":true},
    { "id":"nmmmh_d3_14","type":"choice","num":"D3_14","chapter":2,"chapter_name":"DES","prompt":"Hệ mật DES là tên viết tắt của","options":[{"id":"a","text":"Data Encryption Service"},{"id":"b","text":"Data Encryption Standard."},{"id":"c","text":"Delta Encryption Services."},{"id":"d","text":"Digital Encryption Standard"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230032.png","needs_check":true},
    { "id":"nmmmh_d3_15","type":"choice","num":"D3_15","chapter":2,"chapter_name":"DES","prompt":"Lựa chọn đáp án ĐÚNG về tính xáo trộn trong nguyên lí Shannon","options":[{"id":"a","text":"Tính xáo trộn trong nguyên lí Shannon tạo ra quan hệ của bản rõ và khóa là phi tuyến"},{"id":"b","text":"Tính xáo trộn trong nguyên lí Shannon tạo ra quan hệ của bản mã và khóa là tuyến tính"},{"id":"c","text":"Tính xáo trộn trong nguyên lí Shannon tạo ra quan hệ của bản mã và khóa là phi tuyến"},{"id":"d","text":"Tính xáo trộn trong nguyên lí Shannon tạo ra quan hệ của bản rõ và bản mã là tuyến tính"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230032.png","needs_check":true},
    { "id":"nmmmh_d3_16","type":"choice","num":"D3_16","chapter":2,"chapter_name":"DES","prompt":"DES là hệ mật:","options":[{"id":"a","text":"khóa công khai có 8 cặp khóa vòng"},{"id":"b","text":"khóa bí mật"},{"id":"c","text":"khóa bí mật có 10 khóa vòng"},{"id":"d","text":"khóa bất đối xứng"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230032.png","needs_check":true},
    { "id":"nmmmh_d3_17","type":"choice","num":"D3_17","chapter":2,"chapter_name":"DES","prompt":"Đâu là hệ mật có cấu trúc mạng Feistel?","options":[{"id":"a","text":"DES, Serpent, RC4"},{"id":"b","text":"DES"},{"id":"c","text":"DES, AES, Blowfish"},{"id":"d","text":"RC4"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230125.png","needs_check":true},
    { "id":"nmmmh_d3_18","type":"choice","num":"D3_18","chapter":2,"chapter_name":"DES","prompt":"Kích thước của hoán vị IP trong DES là:","options":[{"id":"a","text":"16 x 16"},{"id":"b","text":"7 x 8"},{"id":"c","text":"8 x 8"},{"id":"d","text":"8 x 6"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230125.png","needs_check":true},
    { "id":"nmmmh_d3_19","type":"choice","num":"D3_19","chapter":2,"chapter_name":"DES","prompt":"Đáp án nào sau đây KHÔNG phải là một chế độ hoạt động của DES?","options":[{"id":"a","text":"Cipher Block Chaining"},{"id":"b","text":"Cipher Feedback"},{"id":"c","text":"Decipher Feedback"},{"id":"d","text":"Electronic Code Book"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230125.png","needs_check":true},
    { "id":"nmmmh_d3_20","type":"choice","num":"D3_20","chapter":2,"chapter_name":"DES","prompt":"Các hộp thế trong DES thay thế","options":[{"id":"a","text":"Một chuỗi 6 bit thành chuỗi 6 bit"},{"id":"b","text":"Một chuỗi 6 bit thành chuỗi 4 bit"},{"id":"c","text":"Một chuỗi 4 bit thành chuỗi 6 bit"},{"id":"d","text":"Một chuỗi 4 bit thành chuỗi 4 bit"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230217.png","needs_check":true},
    { "id":"nmmmh_d3_21","type":"choice","num":"D3_21","chapter":2,"chapter_name":"DES","prompt":"Tripple DES có số lượng khóa khác nhau tối đa là","options":[{"id":"a","text":"1"},{"id":"b","text":"3"},{"id":"c","text":"4"},{"id":"d","text":"2"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230217.png","needs_check":true},
    { "id":"nmmmh_d3_22","type":"choice","num":"D3_22","chapter":2,"chapter_name":"DES","prompt":"Lựa chọn đáp án ĐÚNG về tính khuếch tán trong nguyên lí Shannon","options":[{"id":"a","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit trong bản rõ phải dẫn tới sự thay đổi 1 bit trong bản mã tạo ra và ngược lại"},{"id":"b","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit trong bản rõ phải dẫn tới sự thay đổi một nửa số bit trong bản mã tạo ra và ngược lại"},{"id":"c","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit trong bản rõ phải dẫn tới sự thay đổi 2 bit trong bản mã tạo ra và ngược lại"},{"id":"d","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit trong khóa phải dẫn tới sự thay đổi một nửa số bit trong bản mã tạo ra và ngược lại"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230217.png","needs_check":true},
    { "id":"nmmmh_d3_23","type":"choice","num":"D3_23","chapter":2,"chapter_name":"DES","prompt":"Kích thước khối dữ liệu đầu vào của thuật toán DES là?","options":[{"id":"a","text":"64 bit"},{"id":"b","text":"56 bit"},{"id":"c","text":"48 bit"},{"id":"d","text":"192 bit"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230449.png","needs_check":true},
    { "id":"nmmmh_d3_24","type":"choice","num":"D3_24","chapter":2,"chapter_name":"DES","prompt":"DES là:","options":[{"id":"a","text":"Thuật toán mã dòng có cấu trúc mật mã Feistel"},{"id":"b","text":"Thuật toán mã khối có số vòng thực hiện là 26"},{"id":"c","text":"Thuật toán mã khối sử dụng 16 khóa vòng giống nhau"},{"id":"d","text":"Thuật toán mã khối có cấu trúc mật mã Feistel"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230449.png","needs_check":true},
    { "id":"nmmmh_d3_25","type":"choice","num":"D3_25","chapter":2,"chapter_name":"DES","prompt":"DES có bao nhiêu vòng lặp","options":[{"id":"a","text":"8"},{"id":"b","text":"16"},{"id":"c","text":"10"},{"id":"d","text":"14"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230449.png","needs_check":true},
    { "id":"nmmmh_d3_26","type":"choice","num":"D3_26","chapter":2,"chapter_name":"DES","prompt":"Số hộp thế được dùng trong DES là","options":[{"id":"a","text":"32"},{"id":"b","text":"24"},{"id":"c","text":"8"},{"id":"d","text":"16"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230537.png","needs_check":true},
    { "id":"nmmmh_d3_27","type":"choice","num":"D3_27","chapter":2,"chapter_name":"DES","prompt":"Điều nào là ĐÚNG đối với hàm f trong thuật toán DES?","options":[{"id":"a","text":"Đầu ra của hàm f là một khối 48 bít"},{"id":"b","text":"Hàm f thực hiện mở rộng khóa, trộn khóa, thay thế, hoán vị"},{"id":"c","text":"Đầu ra của hàm f là các khối 32 bít"},{"id":"d","text":"Quá trình thay thế của hàm f giúp biến đổi 32 bít đầu vào thành 32 bít đầu ra"}],"answer":"c","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230729.png","needs_check":false},
    { "id":"nmmmh_d3_28","type":"choice","num":"D3_28","chapter":2,"chapter_name":"DES","prompt":"Đâu là kiến trúc mạng Feistel? (Xem 4 sơ đồ được đánh số (1), (2), (3), (4) trong ảnh)","image":"images/nmmmh/source_crops/de3/d3_28_diagrams.png","options":[{"id":"a","text":"3"},{"id":"b","text":"4"},{"id":"c","text":"1"},{"id":"d","text":"2"}],"answer":"d","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230615.png","needs_check":false},
    { "id":"nmmmh_d3_29","type":"choice","num":"D3_29","chapter":2,"chapter_name":"DES","prompt":"Lựa chọn khẳng định SAI về mật mã khóa đối xứng","options":[{"id":"a","text":"Trong mật mã khóa đối xứng, khóa mã hóa và khóa giải mã là giống nhau hoặc dễ dàng suy ra nhau."},{"id":"b","text":"Khóa mã hóa của mật mã khóa đối xứng cần phải giữ bí mật và được bên gửi và nhận trao đổi trên kênh truyền an toàn."},{"id":"c","text":"Mật mã khóa đối xứng thường có khả năng mã hóa/giải mã thông điệp nhanh hơn mật mã khóa bất đối xứng."},{"id":"d","text":"Khóa của mật mã khóa đối xứng là cặp (khóa riêng; khóa công khai)."}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230615.png","needs_check":true},
    { "id":"nmmmh_d3_30","type":"choice","num":"D3_30","chapter":2,"chapter_name":"DES","prompt":"Phát biểu nào dưới đây về độ an toàn của hệ thống mật mã theo nguyên lí Kerckhoffs là ĐÚNG?","options":[{"id":"a","text":"Phụ thuộc vào việc giữ bí mật khóa mã/khóa riêng."},{"id":"b","text":"Phụ thuộc vào độ phức tạp tính toán khi thực hiện thuật toán giải mã."},{"id":"c","text":"Phụ thuộc vào việc giữ bí mật của khóa công khai và thuật toán mã hóa"},{"id":"d","text":"Phụ thuộc vào việc giữ bí mật thuật toán mã hóa"}],"answer":"","source_set":"Đề 3","source_image":"Screenshot 2026-08-23 230626.png","needs_check":true}
  ]
};
