// Dữ liệu Đề 1 - Nhập môn mật mã học
// Nguồn: Đề NMMMH(xin được)/Đề 1 (24 ảnh)
// Đáp án để trống vì ảnh nguồn không đánh dấu đáp án đúng – người dùng rà và bổ sung sau.
// File này được index.html đọc và tự nạp vào IndexedDB một lần duy nhất.

var NMMMH_DE1_DATA = {
  subjectId: 'nmmmh',
  subjectName: 'Nhập môn mật mã học',
  subjectIcon: '🔐',
  subjectColor: '#0ea5e9',
  seedVersion: 1,  // tăng số này nếu muốn force re-seed khi có cập nhật
  questions: [
    {"id":"nmmmh_1","type":"choice","num":"1","chapter":1,"chapter_name":"AES","prompt":"Giả sử khóa AES dạng hexa là K = 1B C0 23 8A F6 43 5E 94 AB 5C 50 BF 82 35 EB 5F. Chọn giá trị đúng cho w[3].","options":[{"id":"a","text":"(F6 43 5E 94)"},{"id":"b","text":"(82 35 EB 5F)"},{"id":"c","text":"(1B C0 23 8A)"},{"id":"d","text":"(AB 5C 50 BF)"}],"answer":"","source_image":"Screenshot 2026-08-30 223050.png","needs_check":true},
    {"id":"nmmmh_2","type":"choice","num":"2","chapter":1,"chapter_name":"AES - ShiftRows","prompt":"Cho biết giá trị của x₁₂ và x₃₁ sau khi thực hiện bước ShiftRows (xem sơ đồ minh họa).","image":"images/nmmmh/q_shiftrows.png","options":[{"id":"a","text":"26, AF"},{"id":"b","text":"A3, B2"},{"id":"c","text":"3F, 46"},{"id":"d","text":"A3, 87"}],"answer":"","source_image":"Screenshot 2026-08-30 223143.png","needs_check":true},
    {"id":"nmmmh_3","type":"choice","num":"3","chapter":1,"chapter_name":"AES - xtime","prompt":"Tính xtime(39) theo hệ hexa.","options":[{"id":"a","text":"69"},{"id":"b","text":"72"},{"id":"c","text":"68"},{"id":"d","text":"67"}],"answer":"","source_image":"Screenshot 2026-08-30 223215.png","needs_check":true},
    {"id":"nmmmh_4","type":"choice","num":"4","chapter":1,"chapter_name":"AES - SubByte","prompt":"Trong hệ mật AES với bảng Sbox và sơ đồ SubByte (xem ảnh), hãy tìm giá trị của s₁₃.","image":"images/nmmmh/q_subbyte.png","options":[{"id":"a","text":"AA"},{"id":"b","text":"05"},{"id":"c","text":"47"},{"id":"d","text":"F7"}],"answer":"","source_image":"Screenshot 2026-08-30 223258.png","needs_check":true},
    {"id":"nmmmh_5","type":"choice","num":"5","chapter":1,"chapter_name":"AES - MixColumns","prompt":"Tính giá trị của x₁₃ trong vòng tính MixColumns của hệ mật AES (xem sơ đồ phép nhân ma trận trong ảnh).","image":"images/nmmmh/q_mixcolumns.png","options":[{"id":"a","text":"B1"},{"id":"b","text":"E3"},{"id":"c","text":"A3"},{"id":"d","text":"23"}],"answer":"","source_image":"Screenshot 2026-08-30 223327.png","needs_check":true},
    {"id":"nmmmh_6","type":"choice","num":"6","chapter":2,"chapter_name":"Hệ mã khối","prompt":"Hệ mã nào sau đây là hệ mã khối?","options":[{"id":"a","text":"DES, RC4, RC5."},{"id":"b","text":"AES, Affine, RC4."},{"id":"c","text":"DES, AES, Ceasar."},{"id":"d","text":"DES, AES"}],"answer":"","source_image":"Screenshot 2026-08-30 223337.png","needs_check":true},
    {"id":"nmmmh_7","type":"choice","num":"7","chapter":2,"chapter_name":"Kiến trúc mạng SPN","prompt":"Đâu là kiến trúc mạng SPN? (Xem 4 sơ đồ được đánh số (1), (2), (3), (4) trong ảnh)","image":"images/nmmmh/q_spn.png","options":[{"id":"a","text":"2, 2"},{"id":"b","text":"2, 3, 4"},{"id":"c","text":"3, 4"},{"id":"d","text":"2, 3"}],"answer":"","source_image":"Screenshot 2026-08-30 223712.png","needs_check":true},
    {"id":"nmmmh_8","type":"choice","num":"8","chapter":3,"chapter_name":"Shannon - Tính khuếch tán","prompt":"Lựa chọn đáp án ĐÚNG về tính khuếch tán trong nguyên lý Shannon.","options":[{"id":"a","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit bản rõ → thay đổi 2 bit bản mã và ngược lại"},{"id":"b","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit bản rõ → thay đổi 1 bit bản mã và ngược lại"},{"id":"c","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit bản rõ → thay đổi một nửa số bit bản mã và ngược lại"},{"id":"d","text":"Tính khuếch tán yêu cầu khi thay đổi 1 bit khóa → thay đổi một nửa số bit bản mã và ngược lại"}],"answer":"","source_image":"Screenshot 2026-08-30 223746.png","needs_check":true},
    {"id":"nmmmh_9","type":"choice","num":"9","chapter":3,"chapter_name":"Tấn công mật mã","prompt":"Kẻ tấn công thám mã để tìm khóa từ một số thông điệp được mã hóa, đó là hình thức tấn công nào?","options":[{"id":"a","text":"Tấn công chỉ với bản rõ"},{"id":"b","text":"Tấn công chỉ với bản mã"},{"id":"c","text":"Tấn công với bản rõ đã biết"},{"id":"d","text":"Tấn công với bản mã được chọn"}],"answer":"","source_image":"Screenshot 2026-08-30 223746.png","needs_check":true},
    {"id":"nmmmh_10","type":"choice","num":"10","chapter":1,"chapter_name":"AES - InvShiftRows","prompt":"Hãy cho biết giá trị của x₂₃ và x₀₁ sau khi thực hiện InvShiftRows (xem sơ đồ minh họa).","image":"images/nmmmh/q_invshiftrows.png","options":[{"id":"a","text":"9F, 10"},{"id":"b","text":"20, 10"},{"id":"c","text":"4D, 10"},{"id":"d","text":"4D, 5B"}],"answer":"","source_image":"Screenshot 2026-08-30 223820.png","needs_check":true},
    {"id":"nmmmh_11","type":"choice","num":"11","chapter":1,"chapter_name":"AES - xtime","prompt":"Tính xtime(A5) theo hệ hexa.","options":[{"id":"a","text":"41"},{"id":"b","text":"B1"},{"id":"c","text":"11"},{"id":"d","text":"51"}],"answer":"","source_image":"Screenshot 2026-08-30 223847.png","needs_check":true},
    {"id":"nmmmh_12","type":"choice","num":"12","chapter":2,"chapter_name":"Mạng Feistel - Nhược điểm","prompt":"Nhược điểm của mạng Feistel là","options":[{"id":"a","text":"Cấu trúc Feistel chỉ dùng để mã hóa dữ liệu nhỏ."},{"id":"b","text":"Mỗi vòng mã chỉ biến đổi nửa khối nên cần nhiều vòng hơn, làm giảm tốc độ mã."},{"id":"c","text":"Quá trình mã và giải mã đồng nhất nên dễ tấn công hơn."},{"id":"d","text":"Chỉ dùng phép thế trong mã hóa dữ liệu"}],"answer":"","source_image":"Screenshot 2026-08-30 223847.png","needs_check":true},
    {"id":"nmmmh_13","type":"choice","num":"13","chapter":4,"chapter_name":"Hệ mã OTP","prompt":"Phát biểu nào về hệ mã OTP sau đây là SAI?","options":[{"id":"a","text":"Là hệ mật có độ mật hoàn thiện"},{"id":"b","text":"|K| < |P|"},{"id":"c","text":"Phép mã và giải mã là đồng nhất."},{"id":"d","text":"Là hệ mật khóa đối xứng."}],"answer":"","source_image":"Screenshot 2026-08-30 223847.png","needs_check":true},
    {"id":"nmmmh_14","type":"choice","num":"14","chapter":1,"chapter_name":"AES - Mở rộng khóa","prompt":"Trong mở rộng khóa AES, SubWord = (AE; FE; 86; 54) và Rcon[j]=(01,00,00,00). Tính g(w[3])","options":[{"id":"a","text":"(A6; FE; 86; 54)"},{"id":"b","text":"(EE; FE; 86; 54)"},{"id":"c","text":"(AF; FE; 86; 54)"},{"id":"d","text":"(EA; FE; 86; 54)"}],"answer":"","source_image":"Screenshot 2026-08-30 223918.png","needs_check":true},
    {"id":"nmmmh_15","type":"choice","num":"15","chapter":1,"chapter_name":"AES - Mở rộng khóa","prompt":"Trong mở rộng khóa AES, w[0]=(12;70;AE;DB) và g(w[3])=(65;07;E0;AB). Tính w[4].","options":[{"id":"a","text":"(87; 70; 5F; 80)"},{"id":"b","text":"(87; 71; 5F; 61)"},{"id":"c","text":"(77; 70; 5F; 80)"},{"id":"d","text":"(77; 77; 4E; 70)"}],"answer":"","source_image":"Screenshot 2026-08-30 223918.png","needs_check":true},
    {"id":"nmmmh_16","type":"choice","num":"16","chapter":1,"chapter_name":"AES - AddRoundKey","prompt":"Trong quá trình mở rộng khóa của hệ mật AES với bản rõ và khóa như hình vẽ, kết quả của AddRoundKey là ma trận trạng thái X. Hãy tính x₂₀.","image":"images/nmmmh/q_addroundkey.png","options":[{"id":"a","text":"42"},{"id":"b","text":"61"},{"id":"c","text":"52"},{"id":"d","text":"21"}],"answer":"","source_image":"Screenshot 2026-08-30 223947.png","needs_check":true},
    {"id":"nmmmh_17","type":"choice","num":"17","chapter":2,"chapter_name":"SPN vs Feistel","prompt":"Phân biệt kiến trúc SPN và Feistel. Đặc điểm của mạng Feistel là gì?","options":[{"id":"a","text":"DES dùng Feistel: Mã hóa và giải mã là ngược nhau."},{"id":"b","text":"Mã và giải mã đồng nhất, chỉ khác thứ tự khóa con."},{"id":"c","text":"Mã và giải mã ngược nhau nhưng thứ tự khóa giống nhau."},{"id":"d","text":"Mỗi vòng mã chỉ biến đổi nửa trái của khối dữ liệu."}],"answer":"","source_image":"Screenshot 2026-08-30 224004.png","needs_check":true},
    {"id":"nmmmh_18","type":"choice","num":"18","chapter":1,"chapter_name":"AES - Round Constant","prompt":"Trong mở rộng khóa AES, biết RC[5]=(10). Tính RC[6]","options":[{"id":"a","text":"(20)"},{"id":"b","text":"(40)"},{"id":"c","text":"(80)"},{"id":"d","text":"(08)"}],"answer":"","source_image":"Screenshot 2026-08-30 224004.png","needs_check":true},
    {"id":"nmmmh_19","type":"choice","num":"19","chapter":2,"chapter_name":"Feistel vs SPN","prompt":"Sự khác biệt giữa kiến trúc mạng Feistel so với SPN là?","options":[{"id":"a","text":"Hộp thế có tính phi tuyến."},{"id":"b","text":"Đáp ứng cả xáo trộn và khuếch tán"},{"id":"c","text":"Khối dữ liệu đầu vào của Feistel chia thành hai nửa, qua các vòng xử lí rồi kết hợp lại"},{"id":"d","text":"Số vòng của SPN luôn lớn hơn Feistel"}],"answer":"","source_image":"Screenshot 2026-08-30 224111.png","needs_check":true},
    {"id":"nmmmh_20","type":"choice","num":"20","chapter":1,"chapter_name":"AES - GF(2⁸) nhân","prompt":"Trong AES, tính 42H × 18H trên GF(2⁸) với m(x) = x⁸ + x⁴ + x³ + x + 1.","options":[{"id":"a","text":"6A"},{"id":"b","text":"26"},{"id":"c","text":"2A"},{"id":"d","text":"4C"}],"answer":"","source_image":"Screenshot 2026-08-30 224136.png","needs_check":true},
    {"id":"nmmmh_21","type":"choice","num":"B1_1","chapter":1,"chapter_name":"Rijndael","prompt":"Chọn đáp án SAI về thuật toán mật mã khối Rijndael?","options":[{"id":"a","text":"Khóa có độ dài tối đa là 512 bit"},{"id":"b","text":"Khóa có độ dài tối đa là 256 bit"},{"id":"c","text":"Độ dài khóa phải chia hết cho 32"},{"id":"d","text":"Độ dài khóa không cần bằng với độ dài khối"}],"answer":"","source_image":"Screenshot 2026-08-30 224855.png","needs_check":true},
    {"id":"nmmmh_22","type":"choice","num":"B1_2","chapter":1,"chapter_name":"Rijndael","prompt":"Kích thước khóa tối đa trong thuật toán mã Rijndael là","options":[{"id":"a","text":"1024 bit"},{"id":"b","text":"256 bit"},{"id":"c","text":"64 bit"},{"id":"d","text":"192 bit"}],"answer":"","source_image":"Screenshot 2026-08-30 224855.png","needs_check":true},
    {"id":"nmmmh_23","type":"choice","num":"B1_3","chapter":1,"chapter_name":"AES - Số vòng lặp","prompt":"AES-192 thực hiện bao nhiêu vòng lặp?","options":[{"id":"a","text":"10"},{"id":"b","text":"16"},{"id":"c","text":"8"},{"id":"d","text":"12"}],"answer":"","source_image":"Screenshot 2026-08-30 224855.png","needs_check":true},
    {"id":"nmmmh_24","type":"choice","num":"B1_4","chapter":1,"chapter_name":"AES - Kích thước khóa","prompt":"Kích thước khóa của AES là:","options":[{"id":"a","text":"64/128/192 bit"},{"id":"b","text":"56/64/128 bit"},{"id":"c","text":"128/192/256 bit"},{"id":"d","text":"64/192/256 bit"}],"answer":"","source_image":"Screenshot 2026-08-30 224932.png","needs_check":true},
    {"id":"nmmmh_25","type":"choice","num":"B1_5","chapter":1,"chapter_name":"AES - Phát biểu đúng","prompt":"Phát biểu nào sau đây về hệ mã khối AES là đúng","options":[{"id":"a","text":"Hàm AddRoundkeys giúp đảm bảo tính khuếch tán"},{"id":"b","text":"S-box nhằm tăng tính khuếch tán."},{"id":"c","text":"Hàm ShiftRows và MixColumns tăng trộn tuyến tính để đảm bảo tính khuếch tán."},{"id":"d","text":"Thuật toán AES thực hiện 10 vòng mã hóa đối với khóa 256 bit"}],"answer":"","source_image":"Screenshot 2026-08-30 224932.png","needs_check":true},
    {"id":"nmmmh_26","type":"choice","num":"B1_6","chapter":1,"chapter_name":"Rijndael SAI","prompt":"Chọn đáp án SAI về thuật toán mật mã khối Rijndael?","options":[{"id":"a","text":"Có thể cài đặt trên thẻ thông minh"},{"id":"b","text":"Khóa có thể có độ dài 256 bit."},{"id":"c","text":"Độ dài của khối dữ liệu là 64 bit"},{"id":"d","text":"Các phép biến đổi trong vòng lặp có thể nghịch đảo"}],"answer":"","source_image":"Screenshot 2026-08-30 224932.png","needs_check":true},
    {"id":"nmmmh_27","type":"choice","num":"B1_7","chapter":1,"chapter_name":"AES - Khẳng định SAI","prompt":"Khẳng định nào sau đây về AES là SAI?","options":[{"id":"a","text":"AES hỗ trợ độ dài đối với khối dữ liệu là 128, 192 hoặc 256 bit"},{"id":"b","text":"Khóa của AES phải được giữ bí mật"},{"id":"c","text":"Phép toán cộng và nhân được thực hiện trên GF(2^8)."},{"id":"d","text":"AES dùng mạng SPN trên cấu trúc mảng trạng thái"}],"answer":"","source_image":"Screenshot 2026-08-30 225019.png","needs_check":true},
    {"id":"nmmmh_28","type":"choice","num":"B1_8","chapter":1,"chapter_name":"AES-256 - Khóa mở rộng","prompt":"Kích thước khóa mở rộng của AES-256 là bao nhiêu?","options":[{"id":"a","text":"60 từ"},{"id":"b","text":"52 từ"},{"id":"c","text":"44 từ"},{"id":"d","text":"32 từ"}],"answer":"","source_image":"Screenshot 2026-08-30 225019.png","needs_check":true},
    {"id":"nmmmh_29","type":"choice","num":"B1_9","chapter":1,"chapter_name":"AES - S-box","prompt":"Chọn đáp án ĐÚNG về AES?","options":[{"id":"a","text":"Phép biến đổi ShiftRow và MixColumn đảm bảo tính xáo trộn trên bản mã"},{"id":"b","text":"S-box của AES bao gồm hoán vị của tất cả 256 giá trị 8 bit"},{"id":"c","text":"S-box của AES thực hiện thay thế mỗi byte để đảm bảo tính khuếch tán"},{"id":"d","text":"Mạng SPN trong AES tương tự mạng Feistel trong DES"}],"answer":"","source_image":"Screenshot 2026-08-30 225019.png","needs_check":true},
    {"id":"nmmmh_30","type":"choice","num":"B1_10","chapter":1,"chapter_name":"AES - Hộp thế","prompt":"AES có bao nhiêu hộp thế?","options":[{"id":"a","text":"10"},{"id":"b","text":"12"},{"id":"c","text":"8"},{"id":"d","text":"1"}],"answer":"","source_image":"Screenshot 2026-08-30 225054.png","needs_check":true},
    {"id":"nmmmh_31","type":"choice","num":"B1_11","chapter":1,"chapter_name":"AES - Số vòng lặp","prompt":"Thuật toán AES có bao nhiêu vòng lặp (với khóa 128/192/256 bit)?","options":[{"id":"a","text":"8/12/16"},{"id":"b","text":"8/10/16"},{"id":"c","text":"10/12/14"},{"id":"d","text":"10/12/16"}],"answer":"","source_image":"Screenshot 2026-08-30 225054.png","needs_check":true},
    {"id":"nmmmh_32","type":"choice","num":"B1_12","chapter":1,"chapter_name":"Rijndael SAI 2","prompt":"Chọn đáp án SAI về thuật toán mật mã khối Rijndael?","options":[{"id":"a","text":"Có tổng cộng 25 sự kết hợp về độ dài khóa với độ dài khối dữ liệu đầu vào"},{"id":"b","text":"Độ dài khối dữ liệu chia hết cho 128"},{"id":"c","text":"Độ dài khóa có thể thay đổi tùy chọn"},{"id":"d","text":"Thuật toán Rijndael có thiết kế bị ảnh hưởng bởi thuật toán mã khối Square"}],"answer":"","source_image":"Screenshot 2026-08-30 225054.png","needs_check":true},
    {"id":"nmmmh_33","type":"choice","num":"B1_13","chapter":1,"chapter_name":"AES - Kích thước khối","prompt":"Kích thước khối dữ liệu đầu vào của AES là:","options":[{"id":"a","text":"64 bit"},{"id":"b","text":"192 bit"},{"id":"c","text":"128 bit"},{"id":"d","text":"256 bit"}],"answer":"","source_image":"Screenshot 2026-08-30 225126.png","needs_check":true},
    {"id":"nmmmh_34","type":"choice","num":"B1_14","chapter":1,"chapter_name":"AES - SubByte SAI","prompt":"Khẳng định nào sau đây là SAI?\nA. Ma trận A trong hàm SubByte của AES là ma trận khả nghịch do các hàng của A là độc lập tuyến tính trong GF(2⁸)\nB. Hàm SubByte ngược có công thức là x = (A⁻¹(y + c))⁻¹\nC. Thành phần nghịch đảo của x trong hàm SubBytes() tạo nên tính phi tuyến của nó.\nD. Hàm SubByte có công thức y= Ax⁻¹ + c của AES đảm bảo tính khuếch tán","options":[{"id":"a","text":"A"},{"id":"b","text":"C"},{"id":"c","text":"D"},{"id":"d","text":"B"}],"answer":"","source_image":"Screenshot 2026-08-30 225126.png","needs_check":true},
    {"id":"nmmmh_35","type":"choice","num":"B1_15","chapter":1,"chapter_name":"AES-128 - Khóa mở rộng","prompt":"Kích thước khóa mở rộng của AES-128 là bao nhiêu?","options":[{"id":"a","text":"56 từ"},{"id":"b","text":"44 từ"},{"id":"c","text":"32 từ"},{"id":"d","text":"60 từ"}],"answer":"","source_image":"Screenshot 2026-08-30 225126.png","needs_check":true},
    {"id":"nmmmh_36","type":"choice","num":"B1_16","chapter":1,"chapter_name":"AES - Mảng trạng thái SAI","prompt":"Chọn đáp án SAI?\nA. Mảng trạng thái của AES là các ma trận kích thước 4x4, mỗi phần tử của ma trận là một byte\nB. AES xử lí trên đơn vị cơ bản là một byte\nC. Đa thức tối giản của AES khi thực hiện phép nhân là m(x) = x⁸ + x³ + 1\nD. AES đảm bảo tính xáo trộn nhờ phép SubByte và đảm bảo tính khuếch tán nhờ ShiftRow và Mixcolumn","options":[{"id":"a","text":"B"},{"id":"b","text":"D"},{"id":"c","text":"C"},{"id":"d","text":"A"}],"answer":"","source_image":"Screenshot 2026-08-30 225153.png","needs_check":true},
    {"id":"nmmmh_37","type":"choice","num":"B1_17","chapter":1,"chapter_name":"AES-192 - Khóa mở rộng","prompt":"Kích thước khóa mở rộng của AES-192 là bao nhiêu?","options":[{"id":"a","text":"40 từ"},{"id":"b","text":"52 từ"},{"id":"c","text":"20 từ"},{"id":"d","text":"50 từ"}],"answer":"","source_image":"Screenshot 2026-08-30 225153.png","needs_check":true},
    {"id":"nmmmh_38","type":"choice","num":"B1_18","chapter":1,"chapter_name":"AES-256 - Số vòng lặp","prompt":"AES-256 thực hiện bao nhiêu vòng lặp?","options":[{"id":"a","text":"8"},{"id":"b","text":"16"},{"id":"c","text":"14"},{"id":"d","text":"10"}],"answer":"","source_image":"Screenshot 2026-08-30 225153.png","needs_check":true},
    {"id":"nmmmh_39","type":"choice","num":"B1_19","chapter":1,"chapter_name":"AES-128 - Số vòng lặp","prompt":"AES-128 thực hiện bao nhiêu vòng lặp?","options":[{"id":"a","text":"10"},{"id":"b","text":"14"},{"id":"c","text":"8"},{"id":"d","text":"12"}],"answer":"","source_image":"Screenshot 2026-08-30 225223.png","needs_check":true},
    {"id":"nmmmh_40","type":"choice","num":"B1_20","chapter":1,"chapter_name":"AES - Ma trận trạng thái","prompt":"Kích thước của ma trận trạng thái trong AES là","options":[{"id":"a","text":"Phụ thuộc kích thước khối"},{"id":"b","text":"Phụ thuộc vào mỗi hàm Subbyte, Shiftrow hay Mixcolumn"},{"id":"c","text":"4 x 4"},{"id":"d","text":"Phụ thuộc kích thước khóa"}],"answer":"","source_image":"Screenshot 2026-08-30 225223.png","needs_check":true}
  ]
};
