// Câu hỏi đã chuẩn hóa từ "Đề thi giữa kì.pdf".
// Các câu chỉ có ma trận/sơ đồ mà phần chữ của PDF không đủ sẽ được bổ sung sau cùng với ảnh trang gốc.

var NMMMH_MIDTERM_DATA = {
  subjectId: 'nmmmh', subjectName: 'Nhập môn mật mã học', subjectIcon: '🔐', subjectColor: '#0ea5e9',
  batchKey: 'nmmmh_midterm_seed_v1', sourceSet: 'Đề giữa kì',
  questions: [
    {id:'nmmmh_mid_1',type:'choice',num:'GK_1',chapter:1,chapter_name:'Mật mã cổ điển',prompt:'Hệ mật Affine là hệ mật',options:[{id:'a',text:'Dịch vòng'},{id:'b',text:'Đa biểu'},{id:'c',text:'Đơn biểu'},{id:'d',text:'Thay thế hoán vị'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_2',type:'choice',num:'GK_2',chapter:2,chapter_name:'AES và DES',prompt:'Chọn đáp án SAI.',options:[{id:'a',text:'Khóa của AES có thể có độ dài là 192 bit'},{id:'b',text:'Khóa của AES có thể có độ dài bằng với độ dài của khối dữ liệu'},{id:'c',text:'Khóa của AES có thể có độ dài là 15 byte'},{id:'d',text:'Khóa của DES có độ dài là 56 bit'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_3',type:'multiple_choice',num:'GK_3',chapter:4,chapter_name:'Đường cong Elliptic',prompt:'Điểm nào dưới đây không thuộc đường cong E₁₁(1, 6)?',options:[{id:'a',text:'(8, 8)'},{id:'b',text:'(2, 8)'},{id:'c',text:'(5, 6)'},{id:'d',text:'(7, 2)'}],answer:['b','c'],needs_check:false},
    {id:'nmmmh_mid_4',type:'choice',num:'GK_4',chapter:3,chapter_name:'RC4',prompt:'Trong quá trình tạo dòng khóa của RC4, tại mỗi thời điểm giá trị các ô của mảng S thay đổi như thế nào?',options:[{id:'a',text:'Chỉ thay đổi giá trị 2 ô'},{id:'b',text:'Thay đổi giá trị một nửa mảng S'},{id:'c',text:'Thay đổi toàn bộ mảng S'},{id:'d',text:'Thay đổi giá trị 1 ô'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_5',type:'choice',num:'GK_5',chapter:5,chapter_name:'Số học modulo',prompt:'Đáp án nào là thặng dư bậc hai theo modulo 23?',options:[{id:'a',text:'8'},{id:'b',text:'10'},{id:'c',text:'7'},{id:'d',text:'5'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_6',type:'choice',num:'GK_6',chapter:1,chapter_name:'Khái niệm mật mã',prompt:'Chọn đáp án ĐÚNG về mã hóa dữ liệu.',options:[{id:'a',text:'Mã hóa dữ liệu chỉ được sử dụng trong an ninh quốc phòng'},{id:'b',text:'Mã hóa dữ liệu là sự biến đổi thông tin có thể đọc được thành thông tin không thể đọc được'},{id:'c',text:'Mã hóa dữ liệu là việc sử dụng các hàm một chiều để biến đổi bản rõ thành bản mã'},{id:'d',text:'Mã hóa dữ liệu là việc sử dụng khóa riêng của người gửi để mã hóa bản rõ thành mã'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_7',type:'choice',num:'GK_7',chapter:1,chapter_name:'Mật mã cổ điển',prompt:'Hệ mã nào dưới đây có khả năng chống lại tấn công phân tích tần suất?',options:[{id:'a',text:'Mã đa biểu'},{id:'b',text:'Mã thay thế'},{id:'c',text:'Mã dịch vòng'},{id:'d',text:'Mã Caesar'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_8',type:'choice',num:'GK_8',chapter:2,chapter_name:'AES',prompt:'Chọn đáp án ĐÚNG.',options:[{id:'a',text:'AES có kiến trúc mạng Feistel'},{id:'b',text:'AES có kiến trúc mạng SPN'},{id:'c',text:'AES sử dụng kiến trúc mạng SPN kết hợp mạng Feistel'},{id:'d',text:'AES sử dụng kiến trúc mạng SPN kết hợp với một số loại mạng khác'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_9',type:'choice',num:'GK_9',chapter:2,chapter_name:'Rijndael',prompt:'Khẳng định nào sau đây là SAI đối với thuật toán mã khối Rijndael?',options:[{id:'a',text:'Có tổng cộng 25 sự kết hợp về độ dài khóa với độ dài khối dữ liệu đầu vào'},{id:'b',text:'Độ dài khóa có thể thay đổi tùy chọn'},{id:'c',text:'Chỉ hỗ trợ kích thước khối là bội số của 128 bit'},{id:'d',text:'Thiết kế Rijndael bị ảnh hưởng mạnh bởi thiết kế của mã khối Square'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_10',type:'choice',num:'GK_10',chapter:2,chapter_name:'AES',prompt:'Chọn đáp án ĐÚNG về số vòng AES.',options:[{id:'a',text:'10/12/14 vòng ứng với khóa 64/128/256 bit'},{id:'b',text:'10/12/14 vòng ứng với khóa 128/192/256 bit'},{id:'c',text:'10/12/14 vòng ứng với khóa 128/196/256 bit'},{id:'d',text:'10/12/14 vòng ứng với khóa 64/192/256 bit'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_11',type:'choice',num:'GK_11',chapter:1,chapter_name:'Dịch vụ an toàn thông tin',prompt:'Mật mã có khả năng',options:[{id:'a',text:'Đảm bảo tính toàn vẹn, sẵn sàng, bí mật và xác thực của dữ liệu'},{id:'b',text:'Đảm bảo tính toàn vẹn, sẵn sàng, bí mật của dữ liệu'},{id:'c',text:'Đảm bảo tính sẵn sàng, bí mật của dữ liệu'},{id:'d',text:'Đảm bảo tính toàn vẹn, bí mật và xác thực của dữ liệu'}],answer:'d',needs_check:false},
    {id:'nmmmh_mid_12',type:'choice',num:'GK_12',chapter:2,chapter_name:'AES - xtime',prompt:'Đâu là kết quả của phép xtime(D8)?',options:[{id:'a',text:'B0'},{id:'b',text:'D7'},{id:'c',text:'AB'},{id:'d',text:'5E'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_13',type:'choice',num:'GK_13',chapter:3,chapter_name:'RSA',prompt:'Trong hệ mật RSA, cho p=37, q=19, e=307. Giải mã bản mã c=131 được bản rõ là gì?',options:[{id:'a',text:'628'},{id:'b',text:'11'},{id:'c',text:'17'},{id:'d',text:'19'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_14',type:'choice',num:'GK_14',chapter:3,chapter_name:'RSA',prompt:'Trong hệ mật RSA, cho p=31, q=17, e=7. Chọn bản mã cho bản rõ x=301.',options:[{id:'a',text:'152'},{id:'b',text:'70'},{id:'c',text:'37'},{id:'d',text:'517'}],answer:'d',needs_check:false},
    {id:'nmmmh_mid_15',type:'choice',num:'GK_15',chapter:2,chapter_name:'AES',prompt:'Chọn đáp án ĐÚNG.',options:[{id:'a',text:'Tầng MixColumn giúp tạo nên tính xáo trộn'},{id:'b',text:'S-box thay thế một byte thành một byte khác giúp tạo nên tính xáo trộn'},{id:'c',text:'ShiftRow giúp tạo nên tính xáo trộn'},{id:'d',text:'S-box thay thế một byte thành một byte khác giúp tạo nên tính khuếch tán'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_16',type:'choice',num:'GK_16',chapter:2,chapter_name:'Feistel và SPN',prompt:'Sự khác biệt giữa kiến trúc mạng Feistel so với SPN là?',options:[{id:'a',text:'Khối dữ liệu đầu vào của Feistel được chia thành hai nửa, qua n vòng xử lí rồi kết hợp lại'},{id:'b',text:'Sử dụng hộp thế S để có tính phi tuyến'},{id:'c',text:'Sử dụng kết hợp phép thay thế và hoán vị trong quá trình mã'},{id:'d',text:'Số vòng SPN luôn lớn hơn Feistel'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_17',type:'choice',num:'GK_17',chapter:1,chapter_name:'Hệ mã dòng',prompt:'Chọn đáp án ĐÚNG.',options:[{id:'a',text:'DES là hệ mã dòng'},{id:'b',text:'Vernam là hệ mã bất đối xứng'},{id:'c',text:'Vernam là một hệ mã dòng'},{id:'d',text:'AES là hệ mật bất đối xứng'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_19',type:'choice',num:'GK_19',chapter:5,chapter_name:'Hàm Euler',prompt:'Hàm Phi Euler có tính chất φ(m.n)=φ(m).φ(n) khi',options:[{id:'a',text:'m, n là hợp số'},{id:'b',text:'GCD(m, n)=1'},{id:'c',text:'GCD(m, n) khác 1'},{id:'d',text:'m, n là nghịch đảo của nhau'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_20',type:'choice',num:'GK_20',chapter:3,chapter_name:'ElGamal',prompt:'Dùng ElGamal với p=211, phần tử sinh α=39 của Z*₂₁₁. Người dùng A chọn khóa bí mật a=93. Khóa công khai β là',options:[{id:'a',text:'146'},{id:'b',text:'145'},{id:'c',text:'143'},{id:'d',text:'144'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_21',type:'choice',num:'GK_21',chapter:3,chapter_name:'Ba lô',prompt:'Cho ba lô S=517 và trọng lượng 14, 20, 39, 77, 153, 305, 609. Chọn véc tơ nhị phân đúng.',options:[{id:'a',text:'0,1,1,0,0,1,0'},{id:'b',text:'0,1,0,0,1,1,0'},{id:'c',text:'0,1,1,0,1,1,0'},{id:'d',text:'0,0,1,0,1,1,0'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_22',type:'choice',num:'GK_22',chapter:3,chapter_name:'Merkle-Hellman',prompt:'Khóa công khai Merkle-Hellman a=(18024;14729;22250;27242;8040;13905;31851;29355;15977), bản rõ x=011011101. Bản mã là',options:[{id:'a',text:'106752'},{id:'b',text:'126752'},{id:'c',text:'106755'},{id:'d',text:'106753'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_24',type:'choice',num:'GK_24',chapter:5,chapter_name:'Nhóm cyclic',prompt:'Nhóm nào sau đây là nhóm cyclic?',options:[{id:'a',text:'Z*₂₄₂'},{id:'b',text:'Z*₄₄'},{id:'c',text:'Z*₁₃₃'},{id:'d',text:'Z*₁₅'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_25',type:'choice',num:'GK_25',chapter:2,chapter_name:'DES',prompt:'Các hộp thế trong DES là ánh xạ biến đổi',options:[{id:'a',text:'4 bit thành 6 bit'},{id:'b',text:'2 bit thành 6 bit'},{id:'c',text:'6 bit thành 4 bit'},{id:'d',text:'2 bit thành 4 bit'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_26',type:'choice',num:'GK_26',chapter:3,chapter_name:'Rabin',prompt:'Trong hệ mật Rabin, p=199, q=211, bản rõ m=1731. Khẳng định nào sau đây là SAI?',options:[{id:'a',text:'Các phép toán thực hiện trên Z₄₁₉₈₉'},{id:'b',text:'Bốn nghiệm căn bậc hai là (1731, 40258, 3841, 38148)'},{id:'c',text:'Bản mã c=11524'},{id:'d',text:'Đầu vào thuật toán căn bậc hai dùng c=15142, p=199, q=211'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_28',type:'choice',num:'GK_28',chapter:1,chapter_name:'Hệ mật khóa công khai',prompt:'Chọn đáp án SAI.',options:[{id:'a',text:'Hệ mật khóa công khai ra đời để thay thế các hệ mật khóa bí mật'},{id:'b',text:'Hệ mật đối xứng có khóa mã và khóa giải giống nhau hoặc dễ suy ra nhau'},{id:'c',text:'Hệ mật khóa công khai sử dụng khóa mã hóa và khóa giải mã khác nhau'},{id:'d',text:'Độ an toàn của hệ mật khóa công khai dựa trên độ khó tính toán'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_30',type:'choice',num:'GK_30',chapter:3,chapter_name:'RSA',prompt:'Giả sử RSA có p=19, q=43, e=5. Số điểm bất động ứng với các tham số này là',options:[{id:'a',text:'8'},{id:'b',text:'9'},{id:'c',text:'7'},{id:'d',text:'6'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_31',type:'choice',num:'GK_31',chapter:1,chapter_name:'Mật mã cổ điển',prompt:'Hệ mật Caesar là hệ mật',options:[{id:'a',text:'Bất đối xứng'},{id:'b',text:'Đơn biểu'},{id:'c',text:'Đa biểu'},{id:'d',text:'Thay thế hoán vị'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_32',type:'choice',num:'GK_32',chapter:4,chapter_name:'Đường cong Elliptic',prompt:'Cho y²=x³+x+6 mod 11, P=(2,4), Q=(3,5). P+Q bằng',options:[{id:'a',text:'(7,9)'},{id:'b',text:'(10,9)'},{id:'c',text:'(8,3)'},{id:'d',text:'(7,2)'}],answer:'d',needs_check:false},
    {id:'nmmmh_mid_33',type:'choice',num:'GK_33',chapter:4,chapter_name:'Đường cong Elliptic',prompt:'Cho y²=x³+x+6 mod 11, điểm sinh G=(7,2). A chọn khóa riêng nA=3. Khóa công khai của A là',options:[{id:'a',text:'(5,2)'},{id:'b',text:'(3,5)'},{id:'c',text:'(2,7)'},{id:'d',text:'(5,9)'}],answer:'b',needs_check:false},
    {id:'nmmmh_mid_34',type:'choice',num:'GK_34',chapter:2,chapter_name:'DES',prompt:'Chọn đáp án ĐÚNG.',options:[{id:'a',text:'AES là hệ mật mạnh hơn Triple DES'},{id:'b',text:'Số vòng DES ít hơn số vòng AES'},{id:'c',text:'Triple DES thực hiện ba lần mã hóa bằng DES'},{id:'d',text:'Tốc độ AES chậm hơn Triple DES'}],answer:'c',needs_check:false},
    {id:'nmmmh_mid_35',type:'choice',num:'GK_35',chapter:1,chapter_name:'Mật mã cổ điển',prompt:'Nguyên nhân dẫn đến tấn công tần suất trong hệ mật thay thế đơn biểu cổ điển là',options:[{id:'a',text:'Hàm mã hóa có hàm ngược'},{id:'b',text:'Một từ mã chỉ tương ứng duy nhất với một từ rõ'},{id:'c',text:'Hàm giải mã có hàm ngược'},{id:'d',text:'Độ dư thừa của ngôn ngữ'}],answer:'d',needs_check:false},
    {id:'nmmmh_mid_37',type:'choice',num:'GK_37',chapter:2,chapter_name:'DES',prompt:'DES là tên viết tắt của',options:[{id:'a',text:'Data Encryption Standard'},{id:'b',text:'Decipher Encryption Standard'},{id:'c',text:'Digital Encryption Services'},{id:'d',text:'Description Engine Standard'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_38',type:'choice',num:'GK_38',chapter:5,chapter_name:'Nhóm cyclic',prompt:'Z*₁₄ có số phần tử sinh là bao nhiêu?',options:[{id:'a',text:'2'},{id:'b',text:'5'},{id:'c',text:'4'},{id:'d',text:'6'}],answer:'a',needs_check:false},
    {id:'nmmmh_mid_39',type:'choice',num:'GK_39',chapter:1,chapter_name:'Mật mã cổ điển',prompt:'Hệ mật Vigenere là hệ mật',options:[{id:'a',text:'Bất đối xứng'},{id:'b',text:'Đơn biểu'},{id:'c',text:'Đa biểu'},{id:'d',text:'Dựa trên hệ mật Affine'}],answer:'c',needs_check:false}
  ]
};
