// Dữ liệu đã đọc rõ từ Đề 5: Các chế độ hoạt động của mã khối.
var NMMMH_DE5_DATA = {
  subjectId:'nmmmh', subjectName:'Nhập môn mật mã học', subjectIcon:'🔐', subjectColor:'#0ea5e9',
  batchKey:'nmmmh_seed_v5a', sourceSet:'Đề 5',
  questions:[
    {id:'nmmmh_d5_1',type:'choice',num:'D5_1',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Chế độ mã khối nào có thể xử lí mã hóa song song?',options:[{id:'a',text:'ECB và CTR'},{id:'b',text:'ECB'},{id:'c',text:'OFB và CTR'},{id:'d',text:'CBC và CTR'}],answer:'a',needs_check:false},
    {id:'nmmmh_d5_2',type:'multiple_choice',num:'D5_2',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Chọn các phát biểu ĐÚNG.',options:[{id:'a',text:'Trong CBC, thứ tự bản mã nhận được không quan trọng'},{id:'b',text:'Trong OFB, thay đổi IV làm cùng một bản rõ đầu vào được mã hóa thành bản mã khác'},{id:'c',text:'Trong CFB, thay đổi IV làm cùng một bản rõ đầu vào được mã hóa thành bản mã khác'},{id:'d',text:'Trong ECB, bản mã phụ thuộc cả vector IV và khối bản rõ'}],answer:['b','c'],needs_check:false},
    {id:'nmmmh_d5_3',type:'choice',num:'D5_3',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Chế độ nào cho phép giải mã khối thứ i mà không cần giải mã các khối từ khối 1 tới i-2?',options:[{id:'a',text:'CFB, OFB'},{id:'b',text:'CBC'},{id:'c',text:'CTR, CFB'},{id:'d',text:'ECB, CBC'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_4',type:'choice',num:'D5_4',chapter:2,chapter_name:'ECB',prompt:'Chế độ ECB của mã khối có đặc điểm gì?',options:[{id:'a',text:'Lặp lại trong bản rõ không gây lặp lại trong bản mã'},{id:'b',text:'Lỗi bit trong một khối bản mã ảnh hưởng toàn bộ việc giải mã các khối tiếp theo'},{id:'c',text:'Khối bản mã thứ i dùng làm đầu vào mã hóa khối bản rõ tiếp theo'},{id:'d',text:'Các khối rõ giống nhau luôn sinh khối mã giống nhau khi cùng khóa'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_5',type:'choice',num:'D5_5',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Với cùng khối bản rõ và khóa, luôn thu được cùng một khối bản mã. Điều này đúng với chế độ nào?',options:[{id:'a',text:'ECB và OFB'},{id:'b',text:'Tất cả các chế độ mã khối'},{id:'c',text:'Chỉ ECB'},{id:'d',text:'CTR và CFB'}],answer:'c',needs_check:false},
    {id:'nmmmh_d5_6',type:'choice',num:'D5_6',chapter:2,chapter_name:'ECB',prompt:'Khẳng định nào sau đây là ĐÚNG?',options:[{id:'a',text:'Trong ECB, hai khối rõ giống nhau nhưng IV khác nhau cho hai khối mã khác nhau'},{id:'b',text:'Trong OFB, bản mã chỉ phụ thuộc vào bản rõ đầu vào'},{id:'c',text:'Trong CBC, các khối rõ giống nhau cùng khóa và IV luôn cho các khối mã giống nhau'},{id:'d',text:'Trong ECB, lỗi một hay nhiều bit trong một khối mã đơn lẻ chỉ ảnh hưởng việc giải mã khối đó'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_7',type:'choice',num:'D5_7',chapter:2,chapter_name:'Mã khối',prompt:'Triển khai phần cứng thích hợp với loại nào hơn trong các lựa chọn sau?',options:[{id:'a',text:'DES'},{id:'b',text:'ECB và OFB'},{id:'c',text:'Mã dòng'},{id:'d',text:'AES'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_9',type:'choice',num:'D5_9',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Chế độ làm việc nào sau đây của mã khối sử dụng vector khởi tạo IV?',options:[{id:'a',text:'CBC và ECB'},{id:'b',text:'OFB và ECB'},{id:'c',text:'ECB và CFB'},{id:'d',text:'OFB và CBC'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_10',type:'choice',num:'D5_10',chapter:2,chapter_name:'Chế độ mã khối',prompt:'Những chế độ mã khối nào hoạt động như mã dòng?',options:[{id:'a',text:'CFB, CBC và ECB'},{id:'b',text:'CFB, OFB và CTR'},{id:'c',text:'CFB và ECB'},{id:'d',text:'CBC và OFB'}],answer:'b',needs_check:false},
    {id:'nmmmh_d5_11',type:'choice',num:'D5_11',chapter:2,chapter_name:'CBC',prompt:'Chọn phát biểu ĐÚNG về CBC.',options:[{id:'a',text:'Các khối mã giống nhau khi cùng bản rõ được mã hóa dưới cùng khóa'},{id:'b',text:'Giải mã một khối mã đòi hỏi phải giải mã khối trước đó'},{id:'c',text:'Cơ chế móc xích làm khối mã thứ i phụ thuộc bản rõ thứ i và toàn bộ các khối rõ trước đó'},{id:'d',text:'CBC là viết tắt của Chaining Block Cipher'}],answer:'c',needs_check:false},
    {id:'nmmmh_d5_12',type:'choice',num:'D5_12',chapter:2,chapter_name:'CTR',prompt:'Chọn phát biểu SAI về CTR.',options:[{id:'a',text:'CTR có khả năng song song hóa'},{id:'b',text:'CTR chỉ cần cài đặt thuật toán mã hóa, không cần cài đặt thuật toán giải mã'},{id:'c',text:'CTR mã hóa khối dữ liệu sinh ra từ bộ đếm thay vì trực tiếp mã hóa bản rõ'},{id:'d',text:'CTR có độ an toàn thấp hơn các chế độ mã khối khác'}],answer:'d',needs_check:false},
    {id:'nmmmh_d5_13',type:'choice',num:'D5_13',chapter:2,chapter_name:'CBC',prompt:'Ưu điểm của CBC so với ECB là gì?',options:[{id:'a',text:'CBC dùng IV khiến mã hóa và giải mã đơn giản hơn'},{id:'b',text:'CBC có khả năng che giấu được mẫu lặp của bản rõ'},{id:'c',text:'Lỗi bit trong một khối mã chỉ ảnh hưởng giải mã chính khối đó'},{id:'d',text:'CBC có thể mã hóa song song các phần khác nhau của thông điệp'}],answer:'b',needs_check:false},
    {id:'nmmmh_d5_14',type:'choice',num:'D5_14',chapter:2,chapter_name:'ECB',prompt:'Chọn phát biểu SAI về ECB.',options:[{id:'a',text:'Đổi thứ tự các khối mã tương ứng đổi thứ tự các khối rõ'},{id:'b',text:'Mỗi khối dữ liệu được mã hóa độc lập với các khối khác'},{id:'c',text:'Có thể song song hóa quá trình mã hóa và giải mã'},{id:'d',text:'Lỗi trên một khối bản mã gây ảnh hưởng việc giải mã khối đó và các khối khác'}],answer:'d',needs_check:false}
  ]
};
