// Câu hỏi tự đọc từ Đề 7; giữ nguyên ký hiệu toán học trong dữ liệu.
var NMMMH_DE7_DATA = {
  subjectId:'nmmmh', subjectName:'Nhập môn mật mã học', subjectIcon:'🔐', subjectColor:'#0ea5e9',
  batchKey:'nmmmh_seed_v7', sourceSet:'Đề 7',
  questions:[
    {id:'nmmmh_d7_1',type:'choice',num:'D7_1',chapter:1,chapter_name:'Tổng quan mật mã',prompt:'Đâu là thuật toán mã hóa được xem là có độ an toàn tốt nhất?',options:[{id:'a',text:'DES'},{id:'b',text:'ECC'},{id:'c',text:'AES'},{id:'d',text:'OTP'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_2',type:'choice',num:'D7_2',chapter:1,chapter_name:'Mật mã khóa công khai',prompt:'Phát biểu nào sau đây về hệ mật khóa công khai là ĐÚNG?',options:[{id:'a',text:'Ra đời nhằm thay thế cho các hệ mật khóa bí mật'},{id:'b',text:'Có thể đảm bảo được độ an toàn vô điều kiện'},{id:'c',text:'Có độ an toàn không cao'},{id:'d',text:'Thường được xây dựng dựa trên các bài toán khó đã biết'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_3',type:'choice',num:'D7_3',chapter:1,chapter_name:'Mật mã đối xứng',prompt:'Đâu là ưu điểm của hệ mật đối xứng khi so sánh với hệ mật bất đối xứng?',options:[{id:'a',text:'Tốc độ và số lượng khóa cần dùng'},{id:'b',text:'Tốc độ và phân phối khóa'},{id:'c',text:'Tốc độ'},{id:'d',text:'Tốc độ và các dịch vụ an toàn có thể cung cấp'}],answer:'c',needs_check:false},
    {id:'nmmmh_d7_4',type:'choice',num:'D7_4',chapter:1,chapter_name:'Mật mã khóa công khai',prompt:'Phát biểu nào sau đây KHÔNG ĐÚNG về hệ mật khóa công khai?',options:[{id:'a',text:'Mỗi bên có cặp khóa cho riêng mình'},{id:'b',text:'Rất khó suy ra được khóa giải mã từ biết khóa mã hóa'},{id:'c',text:'Hai bên không thống nhất sử dụng chung một khóa để mã hóa và giải mã'},{id:'d',text:'Hai bên chọn một số ngẫu nhiên rồi tạo cặp khóa để sử dụng chung'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_5',type:'choice',num:'D7_5',chapter:1,chapter_name:'Lý thuyết nhóm',prompt:'Trên nhóm nhân Z^*_{n}, khẳng định nào sau đây là ĐÚNG?',options:[{id:'a',text:'Z^*_{n} = {a ∈ Z_n | 0 < a < n}'},{id:'b',text:'Cấp của Z^*_{n} là số phần tử của nó và bằng φ(n)'},{id:'c',text:'Nếu a ∈ Z^*_{n} thì gcd(a,n)=1 mod n'},{id:'d',text:'a ∈ Z^*_{n}, ord(a)=t và a^s ≡ 1 mod n khi đó s là ước của t'}],answer:'b',needs_check:false},
    {id:'nmmmh_d7_6',type:'choice',num:'D7_6',chapter:1,chapter_name:'Đồng dư Trung Hoa',prompt:'Nếu (b,c)=1 thì hệ phương trình đồng dư x ≡ a mod b; x ≡ a mod c có nghiệm là',options:[{id:'a',text:'x ≡ a mod bc'},{id:'b',text:'x ≡ a mod (b+c)'},{id:'c',text:'x ≡ a mod b.c'},{id:'d',text:'x ≡ a mod c/b'}],answer:'a',needs_check:false},
    {id:'nmmmh_d7_7',type:'choice',num:'D7_7',chapter:1,chapter_name:'Ký hiệu Legendre',prompt:'Cho p là số nguyên tố lẻ, a là số nguyên. Phát biểu nào sau đây là đúng về kí hiệu Legendre (a/p)?',options:[{id:'a',text:'(a/p)=0 nếu a ∈ Q̄_p'},{id:'b',text:'(a/p)=−1 nếu a ∈ Q_p'},{id:'c',text:'(a/p)=1 nếu p | a'},{id:'d',text:'(a/p)=1 nếu a ∈ Q_p'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_8',type:'choice',num:'D7_8',chapter:1,chapter_name:'Ký hiệu Jacobi',prompt:'Khẳng định nào sau đây là ĐÚNG về tính chất của các kí hiệu Jacobi?',options:[{id:'a',text:'Nếu n lẻ thì (2/n)=1 nếu n ≡ ±3 mod 8; và −1 nếu n ≡ ±1 mod 8'},{id:'b',text:'Giả sử m,n lẻ thì (m/n)=−(n/m) nếu m,n ≡3 mod 4; các trường hợp còn lại (m/n)=(n/m)'},{id:'c',text:'Nếu n lẻ và m_1 ≡ m_2 mod n thì (m_1/n)=(m_2/n)'},{id:'d',text:'Khi và chỉ khi n là số nguyên tố lẻ thì ((m_1m_2)/n)=(m_1/n)(m_2/n)'}],answer:'b',needs_check:false},
    {id:'nmmmh_d7_9',type:'choice',num:'D7_9',chapter:4,chapter_name:'Rabin',prompt:'Lựa chọn phát biểu ĐÚNG về số nguyên Blum.',options:[{id:'a',text:'n=pq, p và q là các số nguyên tố thỏa mãn đồng dư 3 mod 4'},{id:'b',text:'n=pq, p và q là các số nguyên tố thỏa mãn đồng dư 5 mod 8'},{id:'c',text:'n=pq, p và q là các số nguyên tố khác nhau thỏa mãn đồng dư 3 mod 4'},{id:'d',text:'n=pq, p và q là các số nguyên tố khác nhau thỏa mãn đồng dư 5 mod 8'}],answer:'c',needs_check:false},
    {id:'nmmmh_d7_10',type:'choice',num:'D7_10',chapter:1,chapter_name:'Số học mô-đun',prompt:'Phát biểu nào sau đây là định lí Fermat nhỏ?',options:[{id:'a',text:'Nếu p là số nguyên tố và a là số nguyên dương nhỏ hơn p, ta luôn có a^p ≡ a mod p'},{id:'b',text:'Nếu p là số nguyên tố và a là số nguyên bất kỳ khác bội của p, ta luôn có a^(p−1) ≡ a mod p'},{id:'c',text:'Nếu p là số nguyên tố và a là số nguyên là bội của p, ta luôn có a^(p−1) ≡ a mod p'},{id:'d',text:'Nếu p là số nguyên tố và a là số nguyên lẻ nhỏ hơn p, ta luôn có a^p ≡ a mod p'}],answer:'a',needs_check:true},
    {id:'nmmmh_d7_11',type:'choice',num:'D7_11',chapter:1,chapter_name:'Thặng dư bậc hai',prompt:'Chọn đáp án ĐÚNG với n=pq, p,q là hai số nguyên tố phân biệt. |Q_n| bằng',options:[{id:'a',text:'3(p−1)(q−1)/4'},{id:'b',text:'(p−1)(q−1)/4'},{id:'c',text:'3(p+1)(q+1)/4'},{id:'d',text:'(p+1)(q+1)/4'}],answer:'b',needs_check:false},
    {id:'nmmmh_d7_12',type:'choice',num:'D7_12',chapter:1,chapter_name:'Thặng dư bậc hai',prompt:'Cho n=p_1^e_1·p_2^e_2·…·p_k^e_k, trong đó p_i là các số nguyên tố lẻ phân biệt và e_i ≥1. Nếu a∈Q_n thì có đúng bao nhiêu căn bậc hai khác nhau theo modulo n?',options:[{id:'a',text:'2k căn bậc hai'},{id:'b',text:'2.k căn bậc hai'},{id:'c',text:'2^(k−1) căn bậc hai'},{id:'d',text:'2^k căn bậc hai'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_13',type:'choice',num:'D7_13',chapter:1,chapter_name:'Thặng dư bậc hai',prompt:'Chọn đáp án ĐÚNG. Cho n=pq, p,q là hai số nguyên tố phân biệt. Khi đó a∈Z^*_{n} là thặng dư bậc hai theo modulo n nếu và chỉ nếu',options:[{id:'a',text:'a ∈ Q_p và a ∈ Q_q'},{id:'b',text:'a ∈ Q_p hoặc a ∈ Q_q'},{id:'c',text:'a ∈ Q̄_p và a ∈ Q̄_q'},{id:'d',text:'a ∈ Q̄_p hoặc a ∈ Q̄_q'}],answer:'a',needs_check:false},
    {id:'nmmmh_d7_14',type:'choice',num:'D7_14',chapter:1,chapter_name:'Hàm Euler',prompt:'Hàm Phi Euler có tính chất Φ(mn)=Φ(m)Φ(n) khi',options:[{id:'a',text:'GCD(m,n) ≠ 1'},{id:'b',text:'GCD(m,n)=1'},{id:'c',text:'m,n là hợp số'},{id:'d',text:'m,n là nghịch đảo của nhau'}],answer:'b',needs_check:false},
    {id:'nmmmh_d7_15',type:'choice',num:'D7_15',chapter:1,chapter_name:'Phần tử sinh',prompt:'α là phần tử sinh của Z^*_{n} nếu',options:[{id:'a',text:'Z^*_{n}={α^i mod n | 0≤i<φ(n)}'},{id:'b',text:'Cấp của α=φ(φ(n))'},{id:'c',text:'α^(φ(n)/p_i) ≠ 1 mod n đối với mỗi phân tích nguyên tố p_i của φ(n)'},{id:'d',text:'Z^*_{n}={α^i mod n | 0≤i≤φ(n)}'}],answer:'c',needs_check:false},
    {id:'nmmmh_d7_16',type:'choice',num:'D7_16',chapter:1,chapter_name:'Phần tử sinh',prompt:'Điều kiện để x là phần tử sinh của Z^*_{37} là',options:[{id:'a',text:'x^(36/2) mod 37 =1 và x^(36/3) mod 37 ≠1'},{id:'b',text:'x^(36/2) mod 37 ≠1 và x^(36/3) mod 37 =1'},{id:'c',text:'x^(36/2) mod 37 =1 và x^(36/3) mod 37 =1'},{id:'d',text:'x^(36/2) mod 37 ≠1 và x^(36/3) mod 37 ≠1'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_17',type:'choice',num:'D7_17',chapter:1,chapter_name:'Thặng dư bậc hai',prompt:'Số các thặng dư bậc 2 theo modulo 41 của Z^*_{41} là',options:[{id:'a',text:'40'},{id:'b',text:'10'},{id:'c',text:'21'},{id:'d',text:'20'}],answer:'d',needs_check:false},
    {id:'nmmmh_d7_18',type:'choice',num:'D7_18',chapter:1,chapter_name:'Hàm Euler',prompt:'Giá trị của Phi Euler Φ(119) là?',options:[{id:'a',text:'118'},{id:'b',text:'96'},{id:'c',text:'90'},{id:'d',text:'113'}],answer:'b',needs_check:false},
    {id:'nmmmh_d7_19',type:'choice',num:'D7_19',chapter:1,chapter_name:'Lý thuyết nhóm',prompt:'Tìm cấp của phần tử a=3 trên Z^*_{61}?',options:[{id:'a',text:'10'},{id:'b',text:'7'},{id:'c',text:'60'},{id:'d',text:'4'}],answer:'a',needs_check:false},
    {id:'nmmmh_d7_20',type:'choice',num:'D7_20',chapter:4,chapter_name:'RSA',prompt:'Tính bảo mật của RSA dựa trên tính khó của',options:[{id:'a',text:'Bài toán tìm số nguyên tố'},{id:'b',text:'Bài toán logarit rời rạc'},{id:'c',text:'Bài toán kiểm tra số nguyên tố'},{id:'d',text:'Bài toán phân tích một số nguyên thành thừa số nguyên tố'}],answer:'d',needs_check:false}
  ]
};
